#!/usr/bin/env node
// Re-measures how heavily each CDLC work type is used and rewrites the USAGE
// block in src/page.html. Run from CI on a schedule, or locally.
//
// Needs three environment variables:
//   JIRA_BASE_URL   e.g. https://skillcatapp.atlassian.net
//   JIRA_EMAIL      the Atlassian account email
//   JIRA_API_TOKEN  https://id.atlassian.com/manage-profile/security/api-tokens
//
// Server-side Basic auth, so none of the browser CORS limits apply. The token
// must never be committed; in CI it comes from GitHub Secrets.

import { readFile, writeFile } from "node:fs/promises";

const BASE = process.env.JIRA_BASE_URL?.replace(/\/$/, "");
const EMAIL = process.env.JIRA_EMAIL;
const TOKEN = process.env.JIRA_API_TOKEN;
const PROJECT = process.env.JIRA_PROJECT ?? "CDLC";
const WINDOW_DAYS = Number(process.env.USAGE_WINDOW_DAYS ?? 365);
const CONCURRENCY = 5;

for (const [name, value] of Object.entries({ JIRA_BASE_URL: BASE, JIRA_EMAIL: EMAIL, JIRA_API_TOKEN: TOKEN })) {
  if (!value) {
    console.error(`Missing ${name}. See the comment at the top of this file.`);
    process.exit(1);
  }
}

const auth = "Basic " + Buffer.from(`${EMAIL}:${TOKEN}`).toString("base64");

async function api(path, init = {}) {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    headers: { Authorization: auth, Accept: "application/json", ...(init.headers ?? {}) },
  });
  if (!res.ok) throw new Error(`${init.method ?? "GET"} ${path} -> ${res.status} ${await res.text()}`);
  return res.json();
}

const count = (jql) =>
  api("/rest/api/3/search/approximate-count", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jql }),
  }).then((r) => r.count);

async function pool(items, n, fn) {
  const out = new Array(items.length);
  let i = 0;
  await Promise.all(
    Array.from({ length: n }, async () => {
      while (i < items.length) {
        const k = i++;
        out[k] = await fn(items[k]);
      }
    })
  );
  return out;
}

const esc = (s) => s.replace(/"/g, '\\"');

console.log(`Reading work types from ${BASE} (${PROJECT})…`);
const types = (await api(`/rest/api/3/project/${PROJECT}/statuses`)).map((t) => t.name);
console.log(`  ${types.length} work types`);

const rows = await pool(types, CONCURRENCY, async (t) => [
  t.trim(),
  await count(`project = ${PROJECT} AND issuetype = "${esc(t)}"`),
  await count(`project = ${PROJECT} AND issuetype = "${esc(t)}" AND created >= -${WINDOW_DAYS}d`),
]);

const totalIssues = await count(`project = ${PROJECT}`);
const active = rows.filter((r) => r[2] > 0).length;
const never = rows.filter((r) => r[1] === 0).length;
console.log(`  ${active} active, ${rows.length - active} dormant (${never} never used), ${totalIssues} issues total`);

const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

const block =
  `/* Ticket counts per work type, measured against all ${totalIssues.toLocaleString()} ${PROJECT} issues on ${today}.\n` +
  `   [total ever, created in the last ${WINDOW_DAYS} days]. A type with no ticket in a year reads Dormant.\n` +
  `   Regenerated by scripts/refresh-usage.mjs — edit that, not this. */\n` +
  `const USAGE = {\n` +
  rows.map(([n, ever, recent]) => `"${esc(n)}":[${ever},${recent}]`).join(",\n") +
  `\n};`;

const SRC = new URL("../src/page.html", import.meta.url);
let page = await readFile(SRC, "utf8");

const pattern = /\/\* Ticket counts per work type[\s\S]*?const USAGE = \{[\s\S]*?\n\};/;
if (!pattern.test(page)) {
  console.error("Could not find the USAGE block in src/page.html — aborting rather than guessing.");
  process.exit(1);
}
const updated = page.replace(pattern, block);

// Also refresh the snapshot date shown in the collapsed provenance note.
const dated = updated.replace(
  /Counts were taken against all\s+[\d,]+ CDLC issues on [^.]+\./,
  `Counts were taken against all ${totalIssues.toLocaleString()} ${PROJECT} issues on ${today}.`
);

if (dated === page) {
  console.log("No change.");
} else {
  await writeFile(SRC, dated, "utf8");
  console.log("src/page.html updated. Run `node build.mjs` to regenerate index.html.");
}
